ccan: Update short_types module to fix warning
Back in 9f64cb2028f8612daa8556cc4831b9b7ce91b171 the ccan/endian module
was updated. Unknown at the time, there were changes made to both the
endian and short_types modules that depnded on each other, or certain
types would be redefined.

 skiboot/ccan/endian/endian.h:336:19: error: redefinition of typedef 'be32' is a
 C11 feature [-Werror,-Wtypedef-redefinition]
 typedef beint32_t be32;
                  ^
 skiboot/ccan/short_types/short_types.h:22:18: note: previous definition is here
 typedef uint32_t be32;
                 ^

By updating the short_types to the latest, we no longer redefine these
types when a module uses both short_types and endian.